export const ROBOTS_SEED = [
  {
    name: 'Maccabot',
    slug: 'maccabot',
    weight_class: '30lb Featherweight',
    weapon_type: 'Spinner',
    description: '30lb featherweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/20462',
  },
  {
    name: 'Trampoline',
    slug: 'trampoline',
    weight_class: '1lb Plastic Antweight',
    weapon_type: 'Spinner',
    description: 'A bot that likes to bounce.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/9751',
  },
  {
    name: 'Control Freak',
    slug: 'control-freak',
    weight_class: '1lb Antweight',
    weapon_type: 'Control Bot',
    description: 'Antweight control bot.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/16240',
  },
  {
    name: 'Split Decision',
    slug: 'split-decision',
    weight_class: '3lb Beetleweight',
    weapon_type: 'Hammer Spinner',
    description: 'Beetleweight with a wiiiiide hammer saw design.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/23819',
  },
  {
    name: 'Power Off',
    slug: 'power-off',
    weight_class: '1lb Antweight',
    weapon_type: 'Spinner',
    description: 'Antweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/9233',
  },
  {
    name: 'Power On',
    slug: 'power-on',
    weight_class: '3lb Beetleweight',
    weapon_type: 'Spinner',
    description: 'Beetleweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/12089',
  },
  {
    name: 'Joyful Timeline',
    slug: 'joyful-timeline',
    weight_class: '1lb Antweight',
    weapon_type: 'Spinner',
    description: 'Antweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/24396',
  },
  {
    name: 'Twitch',
    slug: 'twitch',
    weight_class: '150g Fairyweight',
    weapon_type: 'Spinner',
    description: 'Mini impulse fairyweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/21147',
  },
  {
    name: 'TinkerBot',
    slug: 'tinkerbot',
    weight_class: '150g Fairyweight',
    weapon_type: 'Unknown',
    description: 'Fairyweight competitor.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/18253',
  },
  {
    name: 'Sarissa',
    slug: 'sarissa',
    weight_class: '1lb Antweight',
    weapon_type: 'Wedge Spinner',
    description: 'Cool Thagomizer. Antweight wedge spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/21148',
  },
  {
    name: 'Last Minute',
    slug: 'last-minute',
    weight_class: '1lb Plastic Antweight',
    weapon_type: 'Spinner',
    description: 'Plastic antweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/11960',
  },
  {
    name: 'Last Second',
    slug: 'last-second',
    weight_class: '150g Fairyweight',
    weapon_type: 'Spinner',
    description: 'Fairyweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/26988',
  },
  {
    name: 'Fart',
    slug: 'fart',
    weight_class: '1lb Antweight',
    weapon_type: 'Spinner',
    description: 'Antweight spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/25978',
  },
  {
    name: 'Dumb & Dumber',
    slug: 'dumb-and-dumber',
    weight_class: '12lb Hobbyweight',
    weapon_type: 'Unknown',
    description: '12lb hobbyweight competing at NHRL.',
    rce_url: null,
  },
  {
    name: 'Salt & Pepper',
    slug: 'salt-and-pepper',
    weight_class: '1lb Plastic Antweight',
    weapon_type: 'Spinner',
    description: '2x2 vertical multi spinner.',
    rce_url: 'https://www.robotcombatevents.com/groups/2570/resources/23820',
  },
]
